apiVersion: apps/v1
kind: Deployment
metadata:
  name: debsecops-demo

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: devsecops-demo
  
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
        - name: devsecops-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}