name: CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]


permissions:
  contents: read

jobs:

  Test_and_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install

      - name: Run Unit tests
        run: npm test
      
      - name: SAST CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'
      
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Dependency Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'